name: Format

on:
  push:
    branches:
      - main
      - develop

jobs:
  swift_format:
    name: swiftformat
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format
        run: make format
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.PAT }}
          commit-message: format code
          committer: GitHub <noreply@github.com>
          branch: format-main
          delete-branch: true
          title: 'Format main'
          labels: |
            swiftformat
            automated pr
          draft: false